.build_image_template:
    script:
    - apt update
    - apt install \-y make curl wget python3
    - wget -O get-pip.py https://bootstrap.pypa.io/get-pip.py
    - python3 ./get-pip.py
    - pip install sphinx
    - pip install ./


pages:
    extends: .build_image_template
    script:
    - cd ./docs
    - make html
    - mkdir ../public
    - cp -r ./build/html ../public
    artifacts:
        paths:
        - public
    only:
    - master

.readthedocs:
    extends: .build_image_template
    script:
    - pip install mkdocs

